# Generated by Django 3.2.7 on 2022-02-27 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.CharField(default='Anônimo', max_length=25)),
                ('mensagem', models.CharField(max_length=120)),
            ],
        ),
    ]
