# Generated by Django 3.2.7 on 2022-03-01 02:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('apresentacao', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='data_da_mensagem',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
